name: sagmm
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.1=h7b32b05_0
  - pip=25.2=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.13.1
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - idna==3.4
      - jinja2==3.1.4
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - littleutils==0.2.4
      - markupsafe==2.1.5
      - matplotlib==3.10.5
      - mpmath==1.3.0
      - multidict==6.6.3
      - networkx==3.3
      - numpy==1.26.3
      - ogb==1.3.6
      - outdated==0.2.2
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.0.0
      - propcache==0.3.2
      - psutil==7.0.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.28.1
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - triton==2.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==1.26.13
      - yarl==1.20.1

